knp_gaufrette:
  adapters:
    firebase_docker_compose:
      google_cloud_storage:
        service_id: 'Google_Service_Storage'
        bucket_name: '%env(BUCKET_NAME)%'
        options:
          directory: 'docker-compose'
  filesystems:
    docker_compose:
      adapter: firebase_docker_compose