nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['OPTIONS', 'POST', 'GET']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: '3600'

