nelmio_cors:
  defaults: ~
  paths:
    '^/graphql':
      origin_regex: true
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_methods: ['OPTIONS', 'POST']
      allow_headers: ['Content-Type']
      max_age: 3600
