security:
    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'id'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/v1/login
            stateless: true
            anonymous: true
        api:
            pattern: ^/v1/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
