language: php
php:
  - '7.2'

sudo: false
env:
  - APP_ENV=test

before-install:
  - composer self-update

install:
  - cp .env.dist .env
  - composer install --dev

script:
  - mkdir -p build/logs
  - ./bin/phpunit --coverage-text -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

deploy:
  provider: heroku
  api_key:
    secure: JPw6LuChPcek+2TlgEhH6FLKO+xuNxsuFMSTOw86wzPRRtthv8kNE+RpVbD/87aNaqkuRRBI/U2VedLRMXtnHuX9n+0i7UmxeAKbqOt+/kTAX1EZOclC8HuIS1UlORd9l1GPt79x/cgCL5EGVkXEfAvcj+wVAZFNau03j0/X+7V8auExuWbnSLt7NXzG9iH9CWUIkDymA5YouKxSlNzpMDZQ3A+sl2tqsuPdeagryQWm+LQSIYmwQU2SbmJlaI7DMFQHWXVQSpCpxg6OLoJfDhWqV2zSgOaz88Hb2OvGOEvmlEPGRPN3YlOvEVDIz6HlpV7EJWdTJHdlgnx41Phb7YPE6GwUQRTOp62Zs6IUN84qvHn5DAsS/h/wAhQdeo9bJfCmlzPIiVPYue2ls4WQWDVVwYH2zx5YC1IYVwK70QE2uk4gug5v7w1neaLnAMa28cRdxXs1hUvFVJlttJ7dQq2O7n768XufZaD40FflpEOA7QreX4hk5xgwx5VqFNU5UIYH01NQtJatBCpRT0FmR8SoAa+qUnHJX2NVyMArsfDsu9YnmdKMdUOwgY0k2x3c848PVL7W+Q03eSQ+mshwYJp61bnY14jI0VuhDXQjJ+2wHyGtn2uFCVM116MarN+9NgS3SGuoL4Ov1ffTigKwIbM9tmbXXFQioXoFxbIAzbQ=
  app: okty-server
  on:
    repo: Okty-io/okty-server