version: '3'
services:
    db:
        image: 'mariadb:10.3'
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - 'database:/var/lib/mysql'
        ports:
            - '3306:3306'
    php:
        build: 'docker/php'
        volumes:
            - './:/usr/share/nginx/html'
        working_dir: '/usr/share/nginx/html'
    nginx:
        image: 'okty/nginx:1.14'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=public
        volumes:
            - './:/usr/share/nginx/html'
        ports:
            - '8080:80'
    redis:
        image: redis:4.0.2
        hostname: redis
volumes:
    database: