container_form_index:
    path: /form
    methods: [GET]
    controller: App\Controller\Container\Form\Index::handle

container_form_show:
    path: /form/{id}
    methods: [GET]
    controller: App\Controller\Container\Form\Show::handle
    requirements:
        id: '^[a-zA-Z]+$'

container_build:
    path: /build
    methods: [POST]
    controller: App\Controller\Container\Build::handle
