template_index:
    path: /
    methods: [GET]
    controller: App\Controller\Template\Index::handle

template_show:
    path: /{id}
    methods: [GET]
    controller: App\Controller\Template\Show::handle
    requirements:
        id: '^[a-zA-Z0-9]+$'
