services:
    App\Service\LambdaInterface:
        class: 'App\Service\Lambda'

    App\Repository\ContainerRepositoryInterface:
        alias: 'App\Repository\ContainerRepository'

    App\Repository\TemplateRepositoryInterface:
        alias: 'App\Repository\TemplateRepository'
