Query:
  type: object
  config:
    fields:
      containers:
        type: '[Container!]!'
        description: 'Get list of availables containers'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Container\\Containers", [])'
      container:
        type: 'Container'
        description: 'Get container'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Container\\Container", [args["id"]])'
        args:
          id:
            type: 'String!'
      templates:
        type: '[Template!]!'
        description: 'Get list of availables templates'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Template\\Templates", [])'
      template:
        type: 'Template!'
        description: 'Get a template'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Template\\Template", [args["id"]])'
        args:
          id:
            type: 'String!'
