ContainerConfigField:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      label:
        type: 'String!'
      type:
        type: 'String!'
      base:
        type: 'String!'
      destination:
        type: 'String!'
      value:
        type: 'String!'
      validators:
        type: '[Validator!]!'