Container:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      name:
        type: 'String!'
      image:
        type: 'String!'
      docker:
        type: 'String!'
      version:
        type: 'String!'
      config:
        type: '[ContainerConfig!]!'
