Container:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      name:
        type: 'String!'
      logo:
        type: 'String!'
      config:
        type: '[ContainerConfig!]!'
