ContainerConfigField:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      label:
        type: 'String'
      type:
        type: 'String!'
      base:
        type: 'String'
      destination:
        type: 'String!'
      value:
        type: 'String'
      source:
        type: '[Source!]'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Container\\Source", [value])'
      validators:
        type: '[Validator]'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Container\\Validators", [value])'
