TemplateConfig:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      version:
        type: 'String!'
      volumes:
        type: '[String!]'
      ports:
        type: '[String!]'
      environments:
        type: '[String!]'